 /******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: Ahmed Ehab
 ******************************************************************************/

/**********************************************************************************************************************
 *  INCLUDES
 *********************************************************************************************************************/

#include "Port.h"

/**********************************************************************************************************************
 *  GLOBAL DATA
 *********************************************************************************************************************/

/* PB structure used with Port_Init API */
const Port_ConfigType Port_Configuration = {
		PortConf_PORTA_PIN0_PORT_NUM , PortConf_PORTA_CHANNEL0, PORTA_PIN0_DIRECTION, PORTA_PIN0_INTERNAL_RES, PORTA_PIN0_INITIAL_LEVEL , PORTA_PIN0_MODE , PORTA_PIN0_DIRECTION_CHANGEABLE, PORTA_PIN0_MODE_CHANGEABLE,
		PortConf_PORTA_PIN1_PORT_NUM , PortConf_PORTA_CHANNEL1, PORTA_PIN1_DIRECTION, PORTA_PIN1_INTERNAL_RES, PORTA_PIN1_INITIAL_LEVEL , PORTA_PIN1_MODE , PORTA_PIN1_DIRECTION_CHANGEABLE, PORTA_PIN1_MODE_CHANGEABLE,
		PortConf_PORTA_PIN2_PORT_NUM , PortConf_PORTA_CHANNEL2, PORTA_PIN2_DIRECTION, PORTA_PIN2_INTERNAL_RES, PORTA_PIN2_INITIAL_LEVEL , PORTA_PIN2_MODE , PORTA_PIN2_DIRECTION_CHANGEABLE, PORTA_PIN2_MODE_CHANGEABLE,
		PortConf_PORTA_PIN3_PORT_NUM , PortConf_PORTA_CHANNEL3, PORTA_PIN3_DIRECTION, PORTA_PIN3_INTERNAL_RES, PORTA_PIN3_INITIAL_LEVEL , PORTA_PIN3_MODE , PORTA_PIN3_DIRECTION_CHANGEABLE, PORTA_PIN3_MODE_CHANGEABLE,
		PortConf_PORTA_PIN4_PORT_NUM , PortConf_PORTA_CHANNEL4, PORTA_PIN4_DIRECTION, PORTA_PIN4_INTERNAL_RES, PORTA_PIN4_INITIAL_LEVEL , PORTA_PIN4_MODE , PORTA_PIN4_DIRECTION_CHANGEABLE, PORTA_PIN4_MODE_CHANGEABLE,
		PortConf_PORTA_PIN5_PORT_NUM , PortConf_PORTA_CHANNEL5, PORTA_PIN5_DIRECTION, PORTA_PIN5_INTERNAL_RES, PORTA_PIN5_INITIAL_LEVEL , PORTA_PIN5_MODE , PORTA_PIN5_DIRECTION_CHANGEABLE, PORTA_PIN5_MODE_CHANGEABLE,
		PortConf_PORTA_PIN6_PORT_NUM , PortConf_PORTA_CHANNEL6, PORTA_PIN6_DIRECTION, PORTA_PIN6_INTERNAL_RES, PORTA_PIN6_INITIAL_LEVEL , PORTA_PIN6_MODE , PORTA_PIN6_DIRECTION_CHANGEABLE, PORTA_PIN6_MODE_CHANGEABLE,
		PortConf_PORTA_PIN7_PORT_NUM , PortConf_PORTA_CHANNEL7, PORTA_PIN7_DIRECTION, PORTA_PIN7_INTERNAL_RES, PORTA_PIN7_INITIAL_LEVEL , PORTA_PIN7_MODE , PORTA_PIN7_DIRECTION_CHANGEABLE, PORTA_PIN7_MODE_CHANGEABLE,

		PortConf_PORTB_PIN0_PORT_NUM , PortConf_PORTB_CHANNEL0, PORTB_PIN0_DIRECTION, PORTB_PIN0_INTERNAL_RES, PORTB_PIN0_INITIAL_LEVEL , PORTB_PIN0_MODE , PORTB_PIN0_DIRECTION_CHANGEABLE, PORTB_PIN0_MODE_CHANGEABLE,
		PortConf_PORTB_PIN1_PORT_NUM , PortConf_PORTB_CHANNEL1, PORTB_PIN1_DIRECTION, PORTB_PIN1_INTERNAL_RES, PORTB_PIN1_INITIAL_LEVEL , PORTB_PIN1_MODE , PORTB_PIN1_DIRECTION_CHANGEABLE, PORTB_PIN1_MODE_CHANGEABLE,
		PortConf_PORTB_PIN2_PORT_NUM , PortConf_PORTB_CHANNEL2, PORTB_PIN2_DIRECTION, PORTB_PIN2_INTERNAL_RES, PORTB_PIN2_INITIAL_LEVEL , PORTB_PIN2_MODE , PORTB_PIN2_DIRECTION_CHANGEABLE, PORTB_PIN2_MODE_CHANGEABLE,
		PortConf_PORTB_PIN3_PORT_NUM , PortConf_PORTB_CHANNEL3, PORTB_PIN3_DIRECTION, PORTB_PIN3_INTERNAL_RES, PORTB_PIN3_INITIAL_LEVEL , PORTB_PIN3_MODE , PORTB_PIN3_DIRECTION_CHANGEABLE, PORTB_PIN3_MODE_CHANGEABLE,
		PortConf_PORTB_PIN4_PORT_NUM , PortConf_PORTB_CHANNEL4, PORTB_PIN4_DIRECTION, PORTB_PIN4_INTERNAL_RES, PORTB_PIN4_INITIAL_LEVEL , PORTB_PIN4_MODE , PORTB_PIN4_DIRECTION_CHANGEABLE, PORTB_PIN4_MODE_CHANGEABLE,
		PortConf_PORTB_PIN5_PORT_NUM , PortConf_PORTB_CHANNEL5, PORTB_PIN5_DIRECTION, PORTB_PIN5_INTERNAL_RES, PORTB_PIN5_INITIAL_LEVEL , PORTB_PIN5_MODE , PORTB_PIN5_DIRECTION_CHANGEABLE, PORTB_PIN5_MODE_CHANGEABLE,
		PortConf_PORTB_PIN6_PORT_NUM , PortConf_PORTB_CHANNEL6, PORTB_PIN6_DIRECTION, PORTB_PIN6_INTERNAL_RES, PORTB_PIN6_INITIAL_LEVEL , PORTB_PIN6_MODE , PORTB_PIN6_DIRECTION_CHANGEABLE, PORTB_PIN6_MODE_CHANGEABLE,
		PortConf_PORTB_PIN7_PORT_NUM , PortConf_PORTB_CHANNEL7, PORTB_PIN7_DIRECTION, PORTB_PIN7_INTERNAL_RES, PORTB_PIN7_INITIAL_LEVEL , PORTB_PIN7_MODE , PORTB_PIN7_DIRECTION_CHANGEABLE, PORTB_PIN7_MODE_CHANGEABLE,

		PortConf_PORTC_PIN4_PORT_NUM , PortConf_PORTC_CHANNEL4, PORTC_PIN4_DIRECTION, PORTC_PIN4_INTERNAL_RES, PORTC_PIN4_INITIAL_LEVEL , PORTC_PIN4_MODE , PORTC_PIN4_DIRECTION_CHANGEABLE, PORTC_PIN4_MODE_CHANGEABLE,
		PortConf_PORTC_PIN5_PORT_NUM , PortConf_PORTC_CHANNEL5, PORTC_PIN5_DIRECTION, PORTC_PIN5_INTERNAL_RES, PORTC_PIN5_INITIAL_LEVEL , PORTC_PIN5_MODE , PORTC_PIN5_DIRECTION_CHANGEABLE, PORTC_PIN5_MODE_CHANGEABLE,
		PortConf_PORTC_PIN6_PORT_NUM , PortConf_PORTC_CHANNEL6, PORTC_PIN6_DIRECTION, PORTC_PIN6_INTERNAL_RES, PORTC_PIN6_INITIAL_LEVEL , PORTC_PIN6_MODE , PORTC_PIN6_DIRECTION_CHANGEABLE, PORTC_PIN6_MODE_CHANGEABLE,
		PortConf_PORTC_PIN7_PORT_NUM , PortConf_PORTC_CHANNEL7, PORTC_PIN7_DIRECTION, PORTC_PIN7_INTERNAL_RES, PORTC_PIN7_INITIAL_LEVEL , PORTC_PIN7_MODE , PORTC_PIN7_DIRECTION_CHANGEABLE, PORTC_PIN7_MODE_CHANGEABLE,

		PortConf_PORTD_PIN0_PORT_NUM , PortConf_PORTD_CHANNEL0, PORTD_PIN0_DIRECTION, PORTD_PIN0_INTERNAL_RES, PORTD_PIN0_INITIAL_LEVEL , PORTD_PIN0_MODE , PORTD_PIN0_DIRECTION_CHANGEABLE, PORTD_PIN0_MODE_CHANGEABLE,
		PortConf_PORTD_PIN1_PORT_NUM , PortConf_PORTD_CHANNEL1, PORTD_PIN1_DIRECTION, PORTD_PIN1_INTERNAL_RES, PORTD_PIN1_INITIAL_LEVEL , PORTD_PIN1_MODE , PORTD_PIN1_DIRECTION_CHANGEABLE, PORTD_PIN1_MODE_CHANGEABLE,
		PortConf_PORTD_PIN2_PORT_NUM , PortConf_PORTD_CHANNEL2, PORTD_PIN2_DIRECTION, PORTD_PIN2_INTERNAL_RES, PORTD_PIN2_INITIAL_LEVEL , PORTD_PIN2_MODE , PORTD_PIN2_DIRECTION_CHANGEABLE, PORTD_PIN2_MODE_CHANGEABLE,
		PortConf_PORTD_PIN3_PORT_NUM , PortConf_PORTD_CHANNEL3, PORTD_PIN3_DIRECTION, PORTD_PIN3_INTERNAL_RES, PORTD_PIN3_INITIAL_LEVEL , PORTD_PIN3_MODE , PORTD_PIN3_DIRECTION_CHANGEABLE, PORTD_PIN3_MODE_CHANGEABLE,
		PortConf_PORTD_PIN4_PORT_NUM , PortConf_PORTD_CHANNEL4, PORTD_PIN4_DIRECTION, PORTD_PIN4_INTERNAL_RES, PORTD_PIN4_INITIAL_LEVEL , PORTD_PIN4_MODE , PORTD_PIN4_DIRECTION_CHANGEABLE, PORTD_PIN4_MODE_CHANGEABLE,
		PortConf_PORTD_PIN5_PORT_NUM , PortConf_PORTD_CHANNEL5, PORTD_PIN5_DIRECTION, PORTD_PIN5_INTERNAL_RES, PORTD_PIN5_INITIAL_LEVEL , PORTD_PIN5_MODE , PORTD_PIN5_DIRECTION_CHANGEABLE, PORTD_PIN5_MODE_CHANGEABLE,
		PortConf_PORTD_PIN6_PORT_NUM , PortConf_PORTD_CHANNEL6, PORTD_PIN6_DIRECTION, PORTD_PIN6_INTERNAL_RES, PORTD_PIN6_INITIAL_LEVEL , PORTD_PIN6_MODE , PORTD_PIN6_DIRECTION_CHANGEABLE, PORTD_PIN6_MODE_CHANGEABLE,
		PortConf_PORTD_PIN7_PORT_NUM , PortConf_PORTD_CHANNEL7, PORTD_PIN7_DIRECTION, PORTD_PIN7_INTERNAL_RES, PORTD_PIN7_INITIAL_LEVEL , PORTD_PIN7_MODE , PORTD_PIN7_DIRECTION_CHANGEABLE, PORTD_PIN7_MODE_CHANGEABLE,

		PortConf_PORTE_PIN0_PORT_NUM , PortConf_PORTE_CHANNEL0, PORTE_PIN0_DIRECTION, PORTE_PIN0_INTERNAL_RES, PORTE_PIN0_INITIAL_LEVEL , PORTE_PIN0_MODE , PORTE_PIN0_DIRECTION_CHANGEABLE, PORTE_PIN0_MODE_CHANGEABLE,
		PortConf_PORTE_PIN1_PORT_NUM , PortConf_PORTE_CHANNEL1, PORTE_PIN1_DIRECTION, PORTE_PIN1_INTERNAL_RES, PORTE_PIN1_INITIAL_LEVEL , PORTE_PIN1_MODE , PORTE_PIN1_DIRECTION_CHANGEABLE, PORTE_PIN1_MODE_CHANGEABLE,
		PortConf_PORTE_PIN2_PORT_NUM , PortConf_PORTE_CHANNEL2, PORTE_PIN2_DIRECTION, PORTE_PIN2_INTERNAL_RES, PORTE_PIN2_INITIAL_LEVEL , PORTE_PIN2_MODE , PORTE_PIN2_DIRECTION_CHANGEABLE, PORTE_PIN2_MODE_CHANGEABLE,
		PortConf_PORTE_PIN3_PORT_NUM , PortConf_PORTE_CHANNEL3, PORTE_PIN3_DIRECTION, PORTE_PIN3_INTERNAL_RES, PORTE_PIN3_INITIAL_LEVEL , PORTE_PIN3_MODE , PORTE_PIN3_DIRECTION_CHANGEABLE, PORTE_PIN3_MODE_CHANGEABLE,
		PortConf_PORTE_PIN4_PORT_NUM , PortConf_PORTE_CHANNEL4, PORTE_PIN4_DIRECTION, PORTE_PIN4_INTERNAL_RES, PORTE_PIN4_INITIAL_LEVEL , PORTE_PIN4_MODE , PORTE_PIN4_DIRECTION_CHANGEABLE, PORTE_PIN4_MODE_CHANGEABLE,
		PortConf_PORTE_PIN5_PORT_NUM , PortConf_PORTE_CHANNEL5, PORTE_PIN5_DIRECTION, PORTE_PIN5_INTERNAL_RES, PORTE_PIN5_INITIAL_LEVEL , PORTE_PIN5_MODE , PORTE_PIN5_DIRECTION_CHANGEABLE, PORTE_PIN5_MODE_CHANGEABLE,

		PortConf_PORTF_PIN0_PORT_NUM , PortConf_PORTF_CHANNEL0, PORTF_PIN0_DIRECTION, PORTF_PIN0_INTERNAL_RES, PORTF_PIN0_INITIAL_LEVEL , PORTF_PIN0_MODE , PORTF_PIN0_DIRECTION_CHANGEABLE, PORTF_PIN0_MODE_CHANGEABLE,
		PortConf_PORTF_PIN1_PORT_NUM , PortConf_PORTF_CHANNEL1, PORTF_PIN1_DIRECTION, PORTF_PIN1_INTERNAL_RES, PORTF_PIN1_INITIAL_LEVEL, PORTF_PIN1_MODE , PORTF_PIN1_DIRECTION_CHANGEABLE, PORTF_PIN1_MODE_CHANGEABLE,
		PortConf_PORTF_PIN2_PORT_NUM , PortConf_PORTF_CHANNEL2, PORTF_PIN2_DIRECTION, PORTF_PIN2_INTERNAL_RES, PORTF_PIN2_INITIAL_LEVEL, PORTF_PIN2_MODE , PORTF_PIN2_DIRECTION_CHANGEABLE, PORTF_PIN2_MODE_CHANGEABLE,
		PortConf_PORTF_PIN3_PORT_NUM , PortConf_PORTF_CHANNEL3, PORTF_PIN3_DIRECTION, PORTF_PIN3_INTERNAL_RES, PORTF_PIN3_INITIAL_LEVEL, PORTF_PIN3_MODE , PORTF_PIN3_DIRECTION_CHANGEABLE, PORTF_PIN3_MODE_CHANGEABLE,
		PortConf_PORTF_PIN4_PORT_NUM , PortConf_PORTF_CHANNEL4, PORTF_PIN4_DIRECTION, PORTF_PIN4_INTERNAL_RES, PORTF_PIN4_INITIAL_LEVEL,  PORTF_PIN4_MODE , PORTF_PIN4_DIRECTION_CHANGEABLE, PORTF_PIN4_MODE_CHANGEABLE

};

/**********************************************************************************************************************
 *  END OF FILE: Port_Lcfg.c
 *********************************************************************************************************************/